<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\Container7bY8Kmw\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/Container7bY8Kmw/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/Container7bY8Kmw.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\Container7bY8Kmw\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \Container7bY8Kmw\srcApp_KernelDevDebugContainer([
    'container.build_hash' => '7bY8Kmw',
    'container.build_id' => 'abb4a35d',
    'container.build_time' => 1575825603,
], __DIR__.\DIRECTORY_SEPARATOR.'Container7bY8Kmw');
