<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'globalJS' => [
            'js' => [
                '/build/runtime.js',
                '/build/globalJS.js',
            ],
        ],
        'globalStyle' => [
            'js' => [
                '/build/runtime.js',
            ],
            'css' => [
                '/build/globalStyle.css',
            ],
        ],
    ],
],

]];
